In [1]:
print(5+3)

8


In [7]:
import numpy as np

In [8]:
s = np.array([3,2,5,6,3,4,6])
np.sort(s)

array([2, 3, 3, 4, 5, 6, 6])

In [9]:
np.array([1,2])

array([1, 2])

In [11]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
np.add(1,2)

3

In [13]:
np.abs(-2)

2

In [17]:
a = np.arange(1,10)

In [18]:
a


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.linspace(1,2,10)

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [20]:
np.ceil(2.33)

3.0

In [25]:
print(np.ones(5))

[1. 1. 1. 1. 1.]


In [26]:
print(np.random.rand(5))

[0.51269018 0.77773005 0.49591756 0.24189645 0.8653121 ]


In [28]:
np.zeros([4,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [34]:
arr = np.array([1, 2, 3, 4])
# check size of the array
print("Size:", arr.size)

# check len of the array
print("len:", len(arr))

# check shape of the array
print("Shape:", arr.shape)

# check dtype of the array elements
print("Datatype:", arr.dtype)

# change the dtype to 'float64'
arr = arr.astype('float64')
print(arr)
print("Datatype:", arr.dtype)

# convert array to list
lis = arr.tolist()
print("\nList:", lis)
print(type(lis))

Size: 4
len: 4
Shape: (4,)
Datatype: int32
[1. 2. 3. 4.]
Datatype: float64

List: [1.0, 2.0, 3.0, 4.0]
<class 'list'>


In [35]:
arr = np.asarray([1, 2, 3, 4])

print("Size:", arr.size)

print("len:", len(arr))


print("Shape:", arr.shape)

print("Datatype:", arr.dtype)

arr = arr.astype('float64')
print(arr)
print("Datatype:", arr.dtype)


lis = arr.tolist()
print("\nList:", lis)
print(type(lis))

Size: 4
len: 4
Shape: (4,)
Datatype: int32
[1. 2. 3. 4.]
Datatype: float64

List: [1.0, 2.0, 3.0, 4.0]
<class 'list'>


In [36]:
list_1 = [1, 2, 3, 4]
list_2 = [5, 6, 7, 8]
list_3 = [9, 10, 11, 12]
arr = np.array([list_1, list_2, list_3]) 

In [37]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [38]:
import pandas as pd

In [41]:
pd.DataFrame(arr)

,0,1,2,3
0,1,2,3,4
1,5,6,7,8
2,9,10,11,12


In [45]:
a = [1, 7, 2,8]

myvar = pd.Series(a, index = ["x", "y", "z",'p'])

print(myvar)

x    1
y    7
z    2
p    8
dtype: int64


In [49]:
calories = {"day1": 420, "day2": 380, "day3": 390}

myvar = pd.Series(calories)

print(myvar)

day1    420
day2    380
day3    390
dtype: int64


In [50]:
data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

myvar = pd.DataFrame(data)

print(myvar)

   calories  duration
0       420        50
1       380        40
2       390        45
